[package]
name = "merlin"
version = "2.0.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/dalek-cryptography/merlin"
homepage = "https://docs.rs/merlin"
documentation = "https://docs.rs/merlin"
categories = ["cryptography"]
keywords = ["cryptography", "zero-knowledge", "fiat-shamir", "transcript"]
description = "Composable proof transcripts for public-coin arguments of knowledge"
exclude = [".travis.yml", ".gitignore"]

[package.metadata.docs.rs]
# We need nightly to build docs
features = ["nightly"]

[dependencies]
keccak = { version = "0.2.2", default-features = false }
byteorder = { version = "1.5.0", default-features = false }
zeroize = { version = "1", default-features = false, features = ["zeroize_derive"] }
rand_core = { version = "0.10.1", default-features = false }
hex = {version = "0.4", default-features = false, optional = true}
bytemuck = {version = "1.25.2", features = ["align_offset", "derive"]}
rand = "0.10.3"

[dev-dependencies]
strobe-rs = "0.7"
curve25519-dalek = "2"
rand_chacha = "0.10.0"

[features]
default = ["std"]
nightly = []
debug-transcript = ["hex"]
std = ["byteorder/std"]
